# Generated by Django 6.0.2 on 2026-05-18 12:15

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_approved_at_customuser_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/', validators=[users.models.validate_file_size, users.models.validate_file_extension]),
        ),
    ]
