# Generated by Django 6.0.2 on 2026-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_students', models.IntegerField(default=0)),
                ('placed_students', models.IntegerField(default=0)),
                ('total_companies', models.IntegerField(default=0)),
                ('total_drives', models.IntegerField(default=0)),
                ('avg_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('branch_stats', models.JSONField(default=dict)),
                ('company_stats', models.JSONField(default=dict)),
            ],
        ),
    ]
