# Generated by Django 6.0.2 on 2026-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquery',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
