# Generated by Django 6.0.2 on 2026-05-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('internship', 'Internship'), ('internship_full_time', 'Internship + Full-time'), ('contract', 'Contract')], default='full_time', max_length=30),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='openings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
    ]
