# Generated by Django 6.0.2 on 2026-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_placementdrive_ctc_placementdrive_job_type_and_more'),
        ('users', '0005_skill_companyprofile_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='eligible_branches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='min_cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='selection_stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full-time'), ('internship', 'Internship'), ('parttime', 'Part-time'), ('contract', 'Contract')], default='fulltime', max_length=30),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='placementdrive',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
